### ISSUE TITLE
Questions about the rewards in logger

### ISSUE THREAD

**Issue by JeremyLinky** [StanfordVL/alignment#3]
Hi, I ran your codes with three different configs and obtained three variants. I observe the tensorboard, finding that the trend of  'test_reward' is different from 'test_bench/step_reward'. Could you explain that? BTW, the end steps for each episode is 25, is it normal? Here is my tensorboard. 

![image](https://user-images.githubusercontent.com/50053052/209443927-d0eaa86b-09b2-452e-b59b-6c7c2acdf949.png)

**Comment by zixianma** [comment]
Hi thanks for the questions! It's reasonable that the end steps for all episodes is 25 (I believe the max number of steps is set to 25 by default, and it can remain 25 even if you enable early stopping when the goal is achieved). As for the difference between `test_reward` and `test_bench/step_reward`, it's due to two major differences. First, the reward and benchmark loggers log things a little bit differently: (as far as I remember from my notes) the reward logger resets at the end of each episode whereas the benchmark logger resets only once at the collector's init(), so the trends can be different. Second, the `test_bench/step_reward` additionally divides the episode reward by the number of steps in each episode (i.e. avg reward per step). Please check the code for the reward and benchmark logger as well as `offpolicy_trainer` for your own understanding, and feel free to write your own logger for your purposes! Lmk if you have any other questions, thanks!
